version: '3'
services:
  app:
    container_name: thatblog
    user: '1002:1002'
    restart: always
    build: ./
    ports:
      - '9086:9086'
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    #ports:
    #  - "9081:9081"
